name: heart_monitor
description: "Patient Heart Monitor Simulator"
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.5.0
  provider: ^6.1.5
  get_it: ^8.0.3
  watch_it: ^1.6.5
  wakelock_plus: ^1.3.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/

  fonts:
    - family: VarelaRound
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf                
    - family: RobotoVariable
      fonts:
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf
    - family: EuroStyle
      fonts:
        - asset: assets/fonts/EuroStyle.ttf
    - family: Arial
      fonts:
        - asset: assets/fonts/ArialMdm.ttf
    - family: Nimbus
      fonts:
        - asset: assets/fonts/NimbusSanL-Bol.otf
        
